# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 1f20cd373505b906562ce740e0eea46088deb1dc46c28e4dc298a202a58a206b644a7a231825469be05d04f8614d658cde48cc1b0a4e7bc859a13c2d3fa9b608

test:
  secret_key_base: a9763ccbbef2ada3d44e163a81444643996c9e81419f30ece8c4236e02e8f0c760fb5c686e91d9f4a4c47b93045df23635076d8f33be0396126e637d2a370959

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
